config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static#index"
  get 'input', to: 'static#input'
  get 'notice', to: 'static#notice'
  get 'easing', to: 'static#easing'
  get 'button', to: 'static#button'
  get 'speed', to: 'static#speed'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    # flash[:notice] = "通知のサンプル"
    # flash[:alert] = "アラートのサンプル"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header__links">
    <%= link_to 'Top', root_path %>

    <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Signup', new_user_registration_path %>
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </div>

  <div class="header__links" data-current>
    <%= link_to 'Button', button_path %>
    <%= link_to 'Input', input_path %>
    <%= link_to 'Notice', notice_path %>
  </div>

  <div class="header__links" data-current>
    <%= link_to 'Speed', speed_path %>
    <%= link_to 'Easing', easing_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsdmSampleProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="<%= controller.controller_path %>" data-action="<%= controller.action_name %>">

    <%= render partial: 'layouts/header' %>

    <div class="container">
      <div class="row">
        <div class="col">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

          <div class="mt-5">
            <%= yield %>        
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsdmSampleProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="<%= controller.controller_path %>" data-action="<%= controller.action_name %>">

    <%= render partial: 'layouts/header' %>

    <div class="layout-center">
      <div class="layout-center__inner">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <div class="form">
          <%= yield %>
        </div>
      </div>    
    </div>
  </body>
</html>